name: 12 - Working with Outputs
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "Github Output: $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                cat << EOF
                ${{ toJson(steps.build.outputs )}}
                EOF
                echo "mistake=true" > "$GITHUB_OUTPUT"
                cat << EOF
                ${{ toJson(steps.build.outputs )}}
                EOF
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"
            - name: Print Outputs
              run: |
                cat << EOF
                ${{ needs.build.outputs }}
                EOF
        
